tasks:
    - name: Secrets & configurations
      command: |
        make install &
        make deps &
        docker pull redocly/redoc &
        docker pull swaggerapi/swagger-ui
        eval $(gp env -e)
        echo "$LANGAME_SVC_PROD" > svc.prod.json
        echo "$LANGAME_SVC_DEV" > svc.dev.json
        echo "Setting up Kubernetes..."
        mkdir -p ~/.kube
        echo $KUBECONFIG | python3 -c 'import sys, yaml, json; j=json.loads(sys.stdin.read()); print(yaml.safe_dump(j))' > ~/.kube/config
        export GOOGLE_APPLICATION_CREDENTIALS=./svc.dev.json
        echo "Setting up Docker for Google Cloud..."
        mkdir -p ~/.docker
        cat >~/.docker/config.json <<EOL
        {
          "credHelpers": {
            "gcr.io": "gcloud",
            "us.gcr.io": "gcloud",
            "eu.gcr.io": "gcloud",
            "asia.gcr.io": "gcloud",
            "staging-k8s.gcr.io": "gcloud",
            "marketplace.gcr.io": "gcloud"
          }
        }
        EOL
        
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - aaron-bond.better-comments
    - bungcip.better-toml
    - GitHub.copilot
    - gitpod.gitpod-desktop
    - googlecloudtools.cloudcode
    - hbenl.vscode-test-explorer
    - k--kato.intellij-idea-keybindings
    - mechatroner.rainbow-csv
    - ms-azuretools.vscode-docker
    - ms-kubernetes-tools.vscode-kubernetes-tools
    - ms-vscode-remote.remote-containers
    - ms-vscode-remote.remote-ssh
    - ms-vscode-remote.remote-ssh-edit
    - ms-vscode.test-adapter-converter
    - mushan.vscode-paste-image
    - Perkovec.emoji
    - RandomFractalsInc.vscode-data-preview
    - redhat.vscode-yaml
    - stylelint.vscode-stylelint
    - Tim-Koehler.helm-intellisense
    - toba.vsfire
    - wix.vscode-import-cost
    - zxh404.vscode-proto3
    - golang.go