tasks:
    - name: Install dependencies
      command: |
        export PIP_USER=false
        pip install -r requirements-test.txt
        pip install -r requirements.txt
        pip freeze
    - name: Secrets
      command: |
        eval $(gp env -e)
        echo "$LANGAME_SVC_PROD" > svc.prod.json
        echo "$LANGAME_SVC_DEV" > svc.dev.json
        mkdir -p ~/.kube
        echo $KUBECONFIG | python3 -c 'import sys, yaml, json; j=json.loads(sys.stdin.read()); print(yaml.safe_dump(j))' > ~/.kube/config
    - name: Auth gcloud
      command: |
        gcloud auth login --no-launch-browser
        gcloud projects list
        echo "gcloud config set project [PROJECT_ID]"
        
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - ms-python.python