tasks:
    - name: Install dependencies
      command: |
        export PIP_USER=false
        pip install -r requirements-test.txt
        pip install -r requirements.txt
        pip freeze
    - name: Secrets
      command: |
        eval $(gp env -e)
        echo "$LANGAME_SVC_PROD" > svc.prod.json
        echo "$LANGAME_SVC_DEV" > svc.dev.json
        mkdir -p ~/.kube
        echo $KUBECONFIG | python3 -c 'import sys, yaml, json; j=json.loads(sys.stdin.read()); print(yaml.safe_dump(j))' > ~/.kube/config
    - name: Auth gcloud
      command: |
        gcloud auth login --no-launch-browser
        gcloud projects list
        echo "gcloud config set project [PROJECT_ID]"
        
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - aaron-bond.better-comments
    - bungcip.better-toml
    - GitHub.copilot
    - gitpod.gitpod-desktop
    - googlecloudtools.cloudcode
    - hbenl.vscode-test-explorer
    - k--kato.intellij-idea-keybindings
    - littlefoxteam.vscode-python-test-adapter
    - mechatroner.rainbow-csv
    - ms-azuretools.vscode-docker
    - ms-kubernetes-tools.vscode-kubernetes-tools
    - ms-python.python
    - ms-python.vscode-pylance
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - ms-vscode-remote.remote-containers
    - ms-vscode-remote.remote-ssh
    - ms-vscode-remote.remote-ssh-edit
    - ms-vscode.test-adapter-converter
    - mushan.vscode-paste-image
    - Perkovec.emoji
    - RandomFractalsInc.vscode-data-preview
    - redhat.vscode-yaml
    - stylelint.vscode-stylelint
    - Tim-Koehler.helm-intellisense
    - toba.vsfire
    - wix.vscode-import-cost
    - zxh404.vscode-proto3