version: '3.9'

services:
  ava:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8080:8080
    volumes:
      - ./config.yaml:/app/config.yaml
      - data:/opt
volumes:
  config.yaml:
  data:
