version: '3.7'

services:
  ava:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8080:8080
    volumes:
      - ./svc.dev.json:/etc/secrets/primary/svc.json
    # entrypoint:
    #   - /bin/sh
    #   - -c
    #   - |
    #     echo "Hello from the entrypoint!"
    #     echo "The service is running on port 8080"
    #     while true; do
    #       sleep 1
    #     done
