# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ava/v1/ava.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from protoc_gen_openapiv2.options import annotations_pb2 as protoc__gen__openapiv2_dot_options_dot_annotations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ava/v1/ava.proto',
  package='ava',
  syntax='proto3',
  serialized_options=b'Z\032github.com/langa-me/ava/v1',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x61va/v1/ava.proto\x12\x03\x61va\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"#\n\x10StreamAvaRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"5\n\x11StreamAvaResponse\x12 \n\tcall_info\x18\x01 \x01(\x0b\x32\r.ava.CallInfo\"\x1e\n\x08\x43\x61llInfo\x12\x12\n\nsession_id\x18\x01 \x01(\t2Z\n\x03\x41va\x12S\n\x06Stream\x12\x15.ava.StreamAvaRequest\x1a\x16.ava.StreamAvaResponse\"\x16\x82\xd3\xe4\x93\x02\x10\"\x0b/api/v1/ava:\x01*(\x01\x30\x01\x42\x1cZ\x1agithub.com/langa-me/ava/v1b\x06proto3'
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,protoc__gen__openapiv2_dot_options_dot_annotations__pb2.DESCRIPTOR,])




_STREAMAVAREQUEST = _descriptor.Descriptor(
  name='StreamAvaRequest',
  full_name='ava.StreamAvaRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='ava.StreamAvaRequest.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=138,
)


_STREAMAVARESPONSE = _descriptor.Descriptor(
  name='StreamAvaResponse',
  full_name='ava.StreamAvaResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='call_info', full_name='ava.StreamAvaResponse.call_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=193,
)


_CALLINFO = _descriptor.Descriptor(
  name='CallInfo',
  full_name='ava.CallInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='session_id', full_name='ava.CallInfo.session_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=195,
  serialized_end=225,
)

_STREAMAVARESPONSE.fields_by_name['call_info'].message_type = _CALLINFO
DESCRIPTOR.message_types_by_name['StreamAvaRequest'] = _STREAMAVAREQUEST
DESCRIPTOR.message_types_by_name['StreamAvaResponse'] = _STREAMAVARESPONSE
DESCRIPTOR.message_types_by_name['CallInfo'] = _CALLINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StreamAvaRequest = _reflection.GeneratedProtocolMessageType('StreamAvaRequest', (_message.Message,), {
  'DESCRIPTOR' : _STREAMAVAREQUEST,
  '__module__' : 'ava.v1.ava_pb2'
  # @@protoc_insertion_point(class_scope:ava.StreamAvaRequest)
  })
_sym_db.RegisterMessage(StreamAvaRequest)

StreamAvaResponse = _reflection.GeneratedProtocolMessageType('StreamAvaResponse', (_message.Message,), {
  'DESCRIPTOR' : _STREAMAVARESPONSE,
  '__module__' : 'ava.v1.ava_pb2'
  # @@protoc_insertion_point(class_scope:ava.StreamAvaResponse)
  })
_sym_db.RegisterMessage(StreamAvaResponse)

CallInfo = _reflection.GeneratedProtocolMessageType('CallInfo', (_message.Message,), {
  'DESCRIPTOR' : _CALLINFO,
  '__module__' : 'ava.v1.ava_pb2'
  # @@protoc_insertion_point(class_scope:ava.CallInfo)
  })
_sym_db.RegisterMessage(CallInfo)


DESCRIPTOR._options = None

_AVA = _descriptor.ServiceDescriptor(
  name='Ava',
  full_name='ava.Ava',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=227,
  serialized_end=317,
  methods=[
  _descriptor.MethodDescriptor(
    name='Stream',
    full_name='ava.Ava.Stream',
    index=0,
    containing_service=None,
    input_type=_STREAMAVAREQUEST,
    output_type=_STREAMAVARESPONSE,
    serialized_options=b'\202\323\344\223\002\020\"\013/api/v1/ava:\001*',
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_AVA)

DESCRIPTOR.services_by_name['Ava'] = _AVA

# @@protoc_insertion_point(module_scope)
