# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ava.v1 import ava_pb2 as ava_dot_v1_dot_ava__pb2


class AvaStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Stream = channel.stream_stream(
                '/ava.Ava/Stream',
                request_serializer=ava_dot_v1_dot_ava__pb2.StreamAvaRequest.SerializeToString,
                response_deserializer=ava_dot_v1_dot_ava__pb2.StreamAvaResponse.FromString,
                )


class AvaServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Stream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AvaServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Stream': grpc.stream_stream_rpc_method_handler(
                    servicer.Stream,
                    request_deserializer=ava_dot_v1_dot_ava__pb2.StreamAvaRequest.FromString,
                    response_serializer=ava_dot_v1_dot_ava__pb2.StreamAvaResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ava.Ava', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Ava(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Stream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/ava.Ava/Stream',
            ava_dot_v1_dot_ava__pb2.StreamAvaRequest.SerializeToString,
            ava_dot_v1_dot_ava__pb2.StreamAvaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
