# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ava.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ava.proto',
  package='ava',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tava.proto\x12\x03\x61va\"\x1d\n\nAvaRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1e\n\x0b\x41vaResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2?\n\nAvaService\x12\x31\n\x06GetAva\x12\x0f.ava.AvaRequest\x1a\x10.ava.AvaResponse\"\x00(\x01\x30\x01\x62\x06proto3'
)




_AVAREQUEST = _descriptor.Descriptor(
  name='AvaRequest',
  full_name='ava.AvaRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='ava.AvaRequest.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=47,
)


_AVARESPONSE = _descriptor.Descriptor(
  name='AvaResponse',
  full_name='ava.AvaResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='ava.AvaResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=79,
)

DESCRIPTOR.message_types_by_name['AvaRequest'] = _AVAREQUEST
DESCRIPTOR.message_types_by_name['AvaResponse'] = _AVARESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AvaRequest = _reflection.GeneratedProtocolMessageType('AvaRequest', (_message.Message,), {
  'DESCRIPTOR' : _AVAREQUEST,
  '__module__' : 'ava_pb2'
  # @@protoc_insertion_point(class_scope:ava.AvaRequest)
  })
_sym_db.RegisterMessage(AvaRequest)

AvaResponse = _reflection.GeneratedProtocolMessageType('AvaResponse', (_message.Message,), {
  'DESCRIPTOR' : _AVARESPONSE,
  '__module__' : 'ava_pb2'
  # @@protoc_insertion_point(class_scope:ava.AvaResponse)
  })
_sym_db.RegisterMessage(AvaResponse)



_AVASERVICE = _descriptor.ServiceDescriptor(
  name='AvaService',
  full_name='ava.AvaService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=81,
  serialized_end=144,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetAva',
    full_name='ava.AvaService.GetAva',
    index=0,
    containing_service=None,
    input_type=_AVAREQUEST,
    output_type=_AVARESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_AVASERVICE)

DESCRIPTOR.services_by_name['AvaService'] = _AVASERVICE

# @@protoc_insertion_point(module_scope)
