// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: ava/v1/api.proto

package v1

import (
	context "context"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamAvaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *StreamAvaRequest) Reset() {
	*x = StreamAvaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ava_v1_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamAvaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAvaRequest) ProtoMessage() {}

func (x *StreamAvaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ava_v1_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAvaRequest.ProtoReflect.Descriptor instead.
func (*StreamAvaRequest) Descriptor() ([]byte, []int) {
	return file_ava_v1_api_proto_rawDescGZIP(), []int{0}
}

func (x *StreamAvaRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StreamAvaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CallInfo *CallInfo `protobuf:"bytes,1,opt,name=call_info,json=callInfo,proto3" json:"call_info,omitempty"`
}

func (x *StreamAvaResponse) Reset() {
	*x = StreamAvaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ava_v1_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamAvaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAvaResponse) ProtoMessage() {}

func (x *StreamAvaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ava_v1_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAvaResponse.ProtoReflect.Descriptor instead.
func (*StreamAvaResponse) Descriptor() ([]byte, []int) {
	return file_ava_v1_api_proto_rawDescGZIP(), []int{1}
}

func (x *StreamAvaResponse) GetCallInfo() *CallInfo {
	if x != nil {
		return x.CallInfo
	}
	return nil
}

type CallInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
}

func (x *CallInfo) Reset() {
	*x = CallInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ava_v1_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallInfo) ProtoMessage() {}

func (x *CallInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ava_v1_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallInfo.ProtoReflect.Descriptor instead.
func (*CallInfo) Descriptor() ([]byte, []int) {
	return file_ava_v1_api_proto_rawDescGZIP(), []int{2}
}

func (x *CallInfo) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

var File_ava_v1_api_proto protoreflect.FileDescriptor

var file_ava_v1_api_proto_rawDesc = []byte{
	0x0a, 0x10, 0x61, 0x76, 0x61, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x03, 0x61, 0x76, 0x61, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65,
	0x6e, 0x2d, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x76, 0x32, 0x2f, 0x6f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2c, 0x0a, 0x10, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x41,
	0x76, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x22, 0x3f, 0x0a, 0x11, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x41, 0x76, 0x61,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x09, 0x63, 0x61, 0x6c, 0x6c,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x61, 0x76,
	0x61, 0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x63, 0x61, 0x6c, 0x6c,
	0x49, 0x6e, 0x66, 0x6f, 0x22, 0x29, 0x0a, 0x08, 0x43, 0x61, 0x6c, 0x6c, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x32,
	0x5a, 0x0a, 0x03, 0x41, 0x76, 0x61, 0x12, 0x53, 0x0a, 0x06, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x12, 0x15, 0x2e, 0x61, 0x76, 0x61, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x41, 0x76, 0x61,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x61, 0x76, 0x61, 0x2e, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x41, 0x76, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x16, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x10, 0x22, 0x0b, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31,
	0x2f, 0x61, 0x76, 0x61, 0x3a, 0x01, 0x2a, 0x28, 0x01, 0x30, 0x01, 0x42, 0x91, 0x01, 0x5a, 0x1a,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x61, 0x6e, 0x67, 0x61,
	0x2d, 0x6d, 0x65, 0x2f, 0x61, 0x76, 0x61, 0x2f, 0x76, 0x31, 0x92, 0x41, 0x72, 0x12, 0x48, 0x0a,
	0x03, 0x41, 0x76, 0x61, 0x22, 0x3c, 0x0a, 0x07, 0x6c, 0x61, 0x6e, 0x67, 0x61, 0x6d, 0x65, 0x12,
	0x1f, 0x68, 0x74, 0x74, 0x70, 0x73, 0x3a, 0x2f, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x61, 0x6e, 0x67, 0x61, 0x2d, 0x6d, 0x65, 0x2f, 0x61, 0x76, 0x61,
	0x1a, 0x10, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x40, 0x6c, 0x61, 0x6e, 0x67, 0x61, 0x2e,
	0x6d, 0x65, 0x32, 0x03, 0x31, 0x2e, 0x30, 0x2a, 0x02, 0x01, 0x02, 0x32, 0x10, 0x61, 0x70, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x6a, 0x73, 0x6f, 0x6e, 0x3a, 0x10, 0x61,
	0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x6a, 0x73, 0x6f, 0x6e, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ava_v1_api_proto_rawDescOnce sync.Once
	file_ava_v1_api_proto_rawDescData = file_ava_v1_api_proto_rawDesc
)

func file_ava_v1_api_proto_rawDescGZIP() []byte {
	file_ava_v1_api_proto_rawDescOnce.Do(func() {
		file_ava_v1_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_ava_v1_api_proto_rawDescData)
	})
	return file_ava_v1_api_proto_rawDescData
}

var file_ava_v1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ava_v1_api_proto_goTypes = []interface{}{
	(*StreamAvaRequest)(nil),  // 0: ava.StreamAvaRequest
	(*StreamAvaResponse)(nil), // 1: ava.StreamAvaResponse
	(*CallInfo)(nil),          // 2: ava.CallInfo
}
var file_ava_v1_api_proto_depIdxs = []int32{
	2, // 0: ava.StreamAvaResponse.call_info:type_name -> ava.CallInfo
	0, // 1: ava.Ava.Stream:input_type -> ava.StreamAvaRequest
	1, // 2: ava.Ava.Stream:output_type -> ava.StreamAvaResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ava_v1_api_proto_init() }
func file_ava_v1_api_proto_init() {
	if File_ava_v1_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ava_v1_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamAvaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ava_v1_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamAvaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ava_v1_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ava_v1_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ava_v1_api_proto_goTypes,
		DependencyIndexes: file_ava_v1_api_proto_depIdxs,
		MessageInfos:      file_ava_v1_api_proto_msgTypes,
	}.Build()
	File_ava_v1_api_proto = out.File
	file_ava_v1_api_proto_rawDesc = nil
	file_ava_v1_api_proto_goTypes = nil
	file_ava_v1_api_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AvaClient is the client API for Ava service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AvaClient interface {
	Stream(ctx context.Context, opts ...grpc.CallOption) (Ava_StreamClient, error)
}

type avaClient struct {
	cc grpc.ClientConnInterface
}

func NewAvaClient(cc grpc.ClientConnInterface) AvaClient {
	return &avaClient{cc}
}

func (c *avaClient) Stream(ctx context.Context, opts ...grpc.CallOption) (Ava_StreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Ava_serviceDesc.Streams[0], "/ava.Ava/Stream", opts...)
	if err != nil {
		return nil, err
	}
	x := &avaStreamClient{stream}
	return x, nil
}

type Ava_StreamClient interface {
	Send(*StreamAvaRequest) error
	Recv() (*StreamAvaResponse, error)
	grpc.ClientStream
}

type avaStreamClient struct {
	grpc.ClientStream
}

func (x *avaStreamClient) Send(m *StreamAvaRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *avaStreamClient) Recv() (*StreamAvaResponse, error) {
	m := new(StreamAvaResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AvaServer is the server API for Ava service.
type AvaServer interface {
	Stream(Ava_StreamServer) error
}

// UnimplementedAvaServer can be embedded to have forward compatible implementations.
type UnimplementedAvaServer struct {
}

func (*UnimplementedAvaServer) Stream(Ava_StreamServer) error {
	return status.Errorf(codes.Unimplemented, "method Stream not implemented")
}

func RegisterAvaServer(s *grpc.Server, srv AvaServer) {
	s.RegisterService(&_Ava_serviceDesc, srv)
}

func _Ava_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AvaServer).Stream(&avaStreamServer{stream})
}

type Ava_StreamServer interface {
	Send(*StreamAvaResponse) error
	Recv() (*StreamAvaRequest, error)
	grpc.ServerStream
}

type avaStreamServer struct {
	grpc.ServerStream
}

func (x *avaStreamServer) Send(m *StreamAvaResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *avaStreamServer) Recv() (*StreamAvaRequest, error) {
	m := new(StreamAvaRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Ava_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ava.Ava",
	HandlerType: (*AvaServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _Ava_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "ava/v1/api.proto",
}
