name: Build Docker images, push to Docker Hub

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install, lint and unit tests
      run: |
        echo "IMPLEMENT ME"
    # - uses: google-github-actions/setup-gcloud@master
    #   with:
    #     service_account_key: ${{ secrets.GCP_SA_KEY }}
    #     export_default_credentials: true
    # TODO: push GCR here

    # - name: Deploy to Cloud Run
    #   id: deploy
    #   uses: google-github-actions/deploy-cloudrun@main
    #   with:
    #     service: hello-cloud-run 
    #     image: gcr.io/cloudrun/hello
    #     credentials: ${{ secrets.GCP_SA_KEY }}

    # - name: Use Output
    #   run: curl "${{ steps.deploy.outputs.url }}"